app = "moaclayco"
primary_region = "fra"

[build]

[env]
  PORT = "8080"
  STRIPE_API_VERSION = "2023-08-16"
  STRIPE_WEBHOOK_ACTIVE_VERSION = "2020-08-27"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
