name: Fly Production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a moaclayco --remote-only --config fly-prod.toml --dockerfile Dockerfile-prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
