name: Fly Stage
on:
  push:
    branches:
      - next
      - 'next-**'
jobs:
  deploy:
    name: Deploy app Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a moaclayco-stage --remote-only --config fly-stage.toml --dockerfile Dockerfile-stage
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
